import type { Metadata } from "next";
import { Monomaniac_One } from "next/font/google"
import "./globals.css";
import ToastProvider from "providers/ToastProvider";

const inter = Monomaniac_One({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <ToastProvider>
          {children}
        </ToastProvider>
      </body>
    </html>
  );
}
