import type { Metadata } from "next";
import "./globals.css";
import ToastProvider from "providers/ToastProvider";
import { Geist_Mono } from "next/font/google";
import StoreProvider from "./storeProviders";

const inter = Geist_Mono({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <StoreProvider>
          <ToastProvider>{children}</ToastProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
